### ISSUE TITLE
Dynamic object property, instead of conforming to AutoCompleteItem

### ISSUE THREAD

**Issue by ChaudhryAtif** [rhostem/ng2-simple-autocomplete#5]
How hard would it be to specify which property of the object to display?

That'll will avoid modifying the data to conform to AutoCompleteItem. For example, if the property I want to display is name (instead of value), then I can specify that and it would still work.

[PrimeFaces' AutoComplete](https://www.primefaces.org/primeng/#/autocomplete) does this. It allows you to specify a value for field, which is then used to display the text.

> field - Field of a suggested object to resolve and display.

And it is used like so:
`<p-autoComplete [(ngModel)]="val" [suggestions]="results" (completeMethod)="search($event)" field="name"></p-autoComplete>`

**Comment by rhostem** [comment]
I think that is not so difficult. But I'd like to preserve current way.

The reason why I introduced typescripts's type like `Autocomplete` item is for more clearness. 

- save original value in `value`
- display text in `text` or  `markup`

Picking property of object is a good way. But that picked property could be an object, array, and not proper value for display. And specifying property eventually requires nested property support.

**Comment by ChaudhryAtif** [comment]
@rhostem First, I'd like to say I'm only suggesting things to allow for easier usability, and not all things might be doable. And I'm not trying to change the way you have created the component.

That being said... similar to how the developer has to conform to AutoCompleteItem to make this component be useful, perhaps it should be their task to ensure that the property of the object is a string, and nothing else. You could try and validate if it is a string. If it isn't, display a placeholder (i.e. undefined) or something like that as an alternative.

The object being used could be simple, or complex, and allowing the user to pick a property out of their object might lead to cleaner code for developers. Currently they have to basically create, and manage a new object to be able to use this component.

Let me know what you think.

**Comment by rhostem** [comment]
Yes, clearness is not flexible. To have more flexibility, your suggestion is worth to adopt. But with more flexibility, more chance of error and more work to dev comes together.  When I started to develop this package months ago, I attracted to typescript's clearness from ambiguity of original Javascript. I think that's why I made the component like this.

This [autocomplete](https://www.npmjs.com/package/react-autosuggest#renderSuggestionProp) package(<=React) also supports arbitrary data shape of array, and rendering function for display. If I'm gonna make big update, that will be good reference.
